version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    reviewers: ["leonardocustodio"]
    schedule:
      interval: "weekly"
    labels: [ "dependencies" ]
    groups:
      node:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers: ["leonardocustodio"]
    schedule:
      interval: "weekly"
    labels: [ "gh-actions" ]
    groups:
      gh-actions:
        patterns:
          - "*"
