version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: [ "dependencies" ]
    groups:
      node:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: '/'
    labels: [ "gh-actions" ]
    schedule:
      interval: weekly
    groups:
      gh-actions:
        patterns:
          - "*"
