/**
 * Curated golden DECODE corpus (API_REDESIGN_PLAN P1.1a).
 *
 * Byte sequences with the outcome `decodeCbor` must produce: acceptance
 * (in which case decode->re-encode must reproduce the input bytes exactly)
 * or rejection with a specific `CborError.code`. Covers every reachable
 * throw site in src/decode.ts (including the `checkCanonicalEncoding`
 * re-encode rejections and CborMap.setNext map-ordering errors), each
 * error propagated through nested containers, and the canonical-form
 * accepts that are easy to get wrong.
 *
 * All vectors were machine-verified against the pre-redesign build; the
 * generator (`scripts/generate-vectors.mjs`) re-verifies each expectation
 * and fails loudly on any mismatch before writing
 * `tests/vectors/decode-vectors.json`.
 */

export interface DecodeCorpusEntry {
  name: string;
  hex: string;
  expect: { ok: true } | { ok: false; code: string };
  note: string;
}

export const decodeCorpus: DecodeCorpusEntry[] = [
  {
    name: "reject/Underrun/(empty)",
    hex: "",
    expect: { ok: false, code: "Underrun" },
    note: "empty input: readCbor L159 remaining<1",
  },
  {
    name: "reject/Underrun/18",
    hex: "18",
    expect: { ok: false, code: "Underrun" },
    note: "uint 2-byte head, 0 of 1 arg bytes (L103)",
  },
  {
    name: "reject/Underrun/19",
    hex: "19",
    expect: { ok: false, code: "Underrun" },
    note: "uint 3-byte head, 0 of 2 arg bytes (L112)",
  },
  {
    name: "reject/Underrun/1900",
    hex: "1900",
    expect: { ok: false, code: "Underrun" },
    note: "uint 3-byte head, 1 of 2 arg bytes",
  },
  {
    name: "reject/Underrun/1a000000",
    hex: "1a000000",
    expect: { ok: false, code: "Underrun" },
    note: "uint 5-byte head, 3 of 4 arg bytes (L122)",
  },
  {
    name: "reject/Underrun/1b00000000000000",
    hex: "1b00000000000000",
    expect: { ok: false, code: "Underrun" },
    note: "uint 9-byte head, 7 of 8 arg bytes (L134)",
  },
  {
    name: "reject/Underrun/38",
    hex: "38",
    expect: { ok: false, code: "Underrun" },
    note: "negative 2-byte head truncated",
  },
  {
    name: "reject/Underrun/3b",
    hex: "3b",
    expect: { ok: false, code: "Underrun" },
    note: "negative 9-byte head truncated",
  },
  {
    name: "reject/Underrun/58",
    hex: "58",
    expect: { ok: false, code: "Underrun" },
    note: "bytestring length head truncated",
  },
  {
    name: "reject/Underrun/78",
    hex: "78",
    expect: { ok: false, code: "Underrun" },
    note: "text length head truncated",
  },
  {
    name: "reject/Underrun/98",
    hex: "98",
    expect: { ok: false, code: "Underrun" },
    note: "array count head truncated",
  },
  {
    name: "reject/Underrun/b8",
    hex: "b8",
    expect: { ok: false, code: "Underrun" },
    note: "map count head truncated",
  },
  {
    name: "reject/Underrun/d8",
    hex: "d8",
    expect: { ok: false, code: "Underrun" },
    note: "tag head truncated",
  },
  {
    name: "reject/Underrun/f8",
    hex: "f8",
    expect: { ok: false, code: "Underrun" },
    note: "simple 2-byte head truncated",
  },
  {
    name: "reject/Underrun/f9",
    hex: "f9",
    expect: { ok: false, code: "Underrun" },
    note: "f16 head with no payload (hv25 dataRemaining<2)",
  },
  {
    name: "reject/Underrun/f97e",
    hex: "f97e",
    expect: { ok: false, code: "Underrun" },
    note: "f16 payload 1 of 2 bytes",
  },
  {
    name: "reject/Underrun/fa3fc000",
    hex: "fa3fc000",
    expect: { ok: false, code: "Underrun" },
    note: "f32 payload 3 of 4 bytes",
  },
  {
    name: "reject/Underrun/fb3ff19999999999",
    hex: "fb3ff19999999999",
    expect: { ok: false, code: "Underrun" },
    note: "f64 payload 7 of 8 bytes",
  },
  {
    name: "reject/Underrun/41",
    hex: "41",
    expect: { ok: false, code: "Underrun" },
    note: "bytestring declares 1 body byte, has 0 (L181)",
  },
  {
    name: "reject/Underrun/4401ff02",
    hex: "4401ff02",
    expect: { ok: false, code: "Underrun" },
    note: "bytestring declares 4 body bytes, has 3",
  },
  {
    name: "reject/Underrun/61",
    hex: "61",
    expect: { ok: false, code: "Underrun" },
    note: "text declares 1 body byte, has 0 (L192)",
  },
  {
    name: "reject/Underrun/626f",
    hex: "626f",
    expect: { ok: false, code: "Underrun" },
    note: "text declares 2 body bytes, has 1",
  },
  {
    name: "reject/Underrun/81",
    hex: "81",
    expect: { ok: false, code: "Underrun" },
    note: "array of 1 with no child; nested readCbor hits empty",
  },
  {
    name: "reject/Underrun/8201",
    hex: "8201",
    expect: { ok: false, code: "Underrun" },
    note: "array of 2 missing second child",
  },
  {
    name: "reject/Underrun/a1",
    hex: "a1",
    expect: { ok: false, code: "Underrun" },
    note: "map of 1 missing key",
  },
  {
    name: "reject/Underrun/a101",
    hex: "a101",
    expect: { ok: false, code: "Underrun" },
    note: "map of 1 missing value",
  },
  {
    name: "reject/Underrun/c1",
    hex: "c1",
    expect: { ok: false, code: "Underrun" },
    note: "tag 1 missing content item",
  },
  {
    name: "reject/Underrun/5b0000000100000000",
    hex: "5b0000000100000000",
    expect: { ok: false, code: "Underrun" },
    note: "bytestring length 2^32 is a plain number (< 2^53); body missing -> Underrun",
  },
  {
    name: "reject/Underrun/9bffffffffffffffff",
    hex: "9bffffffffffffffff",
    expect: { ok: false, code: "Underrun" },
    note: "array count 2^64-1 (bigint) loops fine, first missing child underruns",
  },
  {
    name: "reject/Underrun/bbffffffffffffffff",
    hex: "bbffffffffffffffff",
    expect: { ok: false, code: "Underrun" },
    note: "map count bigint, first missing key underruns",
  },
  {
    name: "reject/Underrun/dbffffffffffffffff",
    hex: "dbffffffffffffffff",
    expect: { ok: false, code: "Underrun" },
    note: "tag value 2^64-1 legal (bigint), missing content underruns",
  },
  {
    name: "reject/UnsupportedHeaderValue/1c",
    hex: "1c",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "major 0 headerValue 28 (L152), details.headerValue=28",
  },
  {
    name: "reject/UnsupportedHeaderValue/1d",
    hex: "1d",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "major 0 headerValue 29",
  },
  {
    name: "reject/UnsupportedHeaderValue/1e",
    hex: "1e",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "major 0 headerValue 30",
  },
  {
    name: "reject/UnsupportedHeaderValue/1f",
    hex: "1f",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "major 0 headerValue 31 (would-be indefinite)",
  },
  {
    name: "reject/UnsupportedHeaderValue/3c",
    hex: "3c",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "negative headerValue 28",
  },
  {
    name: "reject/UnsupportedHeaderValue/3f",
    hex: "3f",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "negative headerValue 31",
  },
  {
    name: "reject/UnsupportedHeaderValue/5f",
    hex: "5f",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "indefinite-length bytestring",
  },
  {
    name: "reject/UnsupportedHeaderValue/7f",
    hex: "7f",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "indefinite-length text",
  },
  {
    name: "reject/UnsupportedHeaderValue/9f",
    hex: "9f",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "indefinite-length array",
  },
  {
    name: "reject/UnsupportedHeaderValue/bf",
    hex: "bf",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "indefinite-length map",
  },
  {
    name: "reject/UnsupportedHeaderValue/df",
    hex: "df",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "tag headerValue 31",
  },
  {
    name: "reject/UnsupportedHeaderValue/fc",
    hex: "fc",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "simple headerValue 28",
  },
  {
    name: "reject/UnsupportedHeaderValue/fd",
    hex: "fd",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "simple headerValue 29",
  },
  {
    name: "reject/UnsupportedHeaderValue/fe",
    hex: "fe",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "simple headerValue 30",
  },
  {
    name: "reject/UnsupportedHeaderValue/5c",
    hex: "5c",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "bytestring headerValue 28",
  },
  {
    name: "reject/UnsupportedHeaderValue/5d",
    hex: "5d",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "bytestring headerValue 29",
  },
  {
    name: "reject/UnsupportedHeaderValue/5e",
    hex: "5e",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "bytestring headerValue 30",
  },
  {
    name: "reject/UnsupportedHeaderValue/7c",
    hex: "7c",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "text headerValue 28",
  },
  {
    name: "reject/UnsupportedHeaderValue/7d",
    hex: "7d",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "text headerValue 29",
  },
  {
    name: "reject/UnsupportedHeaderValue/7e",
    hex: "7e",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "text headerValue 30",
  },
  {
    name: "reject/UnsupportedHeaderValue/9c",
    hex: "9c",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "array headerValue 28",
  },
  {
    name: "reject/UnsupportedHeaderValue/9d",
    hex: "9d",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "array headerValue 29",
  },
  {
    name: "reject/UnsupportedHeaderValue/9e",
    hex: "9e",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "array headerValue 30",
  },
  {
    name: "reject/UnsupportedHeaderValue/bc",
    hex: "bc",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "map headerValue 28",
  },
  {
    name: "reject/UnsupportedHeaderValue/bd",
    hex: "bd",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "map headerValue 29",
  },
  {
    name: "reject/UnsupportedHeaderValue/be",
    hex: "be",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "map headerValue 30",
  },
  {
    name: "reject/UnsupportedHeaderValue/dc",
    hex: "dc",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "tag headerValue 28",
  },
  {
    name: "reject/UnsupportedHeaderValue/dd",
    hex: "dd",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "tag headerValue 29",
  },
  {
    name: "reject/UnsupportedHeaderValue/de",
    hex: "de",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "tag headerValue 30",
  },
  {
    name: "reject/UnsupportedHeaderValue/ff",
    hex: "ff",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "standalone break = major 7 headerValue 31",
  },
  {
    name: "reject/NonCanonicalNumeric/1800",
    hex: "1800",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "uint 0 in 2-byte head (value<24, L107)",
  },
  {
    name: "reject/NonCanonicalNumeric/1817",
    hex: "1817",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "uint 23 in 2-byte head - just below the 24 cutoff",
  },
  {
    name: "reject/NonCanonicalNumeric/190017",
    hex: "190017",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "uint 23 in 3-byte head (value<=0xff, L117)",
  },
  {
    name: "reject/NonCanonicalNumeric/1900ff",
    hex: "1900ff",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "uint 255 in 3-byte head - exactly at the <=0xff boundary",
  },
  {
    name: "reject/NonCanonicalNumeric/1a00000017",
    hex: "1a00000017",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "uint 23 in 5-byte head (value<=0xffff, L129)",
  },
  {
    name: "reject/NonCanonicalNumeric/1a0000ffff",
    hex: "1a0000ffff",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "uint 65535 in 5-byte head - exactly at the <=0xffff boundary",
  },
  {
    name: "reject/NonCanonicalNumeric/1b0000000000000017",
    hex: "1b0000000000000017",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "uint 23 in 9-byte head (value<=0xffffffff, L147)",
  },
  {
    name: "reject/NonCanonicalNumeric/1b00000000ffffffff",
    hex: "1b00000000ffffffff",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "uint 2^32-1 in 9-byte head - exactly at the <=0xffffffff boundary",
  },
  {
    name: "reject/NonCanonicalNumeric/3817",
    hex: "3817",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "negative -24 in 2-byte head (same minimality rule, major 1)",
  },
  {
    name: "reject/NonCanonicalNumeric/390017",
    hex: "390017",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "negative 3-byte head non-minimal",
  },
  {
    name: "reject/NonCanonicalNumeric/3900ff",
    hex: "3900ff",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "negative 3-byte head at <=0xff boundary",
  },
  {
    name: "reject/NonCanonicalNumeric/3a00000017",
    hex: "3a00000017",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "negative 5-byte head non-minimal",
  },
  {
    name: "reject/NonCanonicalNumeric/3a0000ffff",
    hex: "3a0000ffff",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "negative 5-byte head at <=0xffff boundary",
  },
  {
    name: "reject/NonCanonicalNumeric/3b0000000000000017",
    hex: "3b0000000000000017",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "negative 9-byte head non-minimal",
  },
  {
    name: "reject/NonCanonicalNumeric/3b00000000ffffffff",
    hex: "3b00000000ffffffff",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "negative 9-byte head at <=0xffffffff boundary",
  },
  {
    name: "reject/NonCanonicalNumeric/5817",
    hex: "5817",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "bytestring LENGTH 23 in 2-byte head - same validation applies to length heads; fires before body underrun",
  },
  {
    name: "reject/NonCanonicalNumeric/590001ff",
    hex: "590001ff",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "bytestring length 1 in 3-byte head (body byte present but head check fires first)",
  },
  {
    name: "reject/NonCanonicalNumeric/7817",
    hex: "7817",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "text length 23 in 2-byte head",
  },
  {
    name: "reject/NonCanonicalNumeric/9800",
    hex: "9800",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "array count 0 in 2-byte head",
  },
  {
    name: "reject/NonCanonicalNumeric/b800",
    hex: "b800",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "map count 0 in 2-byte head",
  },
  {
    name: "reject/NonCanonicalNumeric/d800",
    hex: "d800",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "tag 0 in 2-byte head",
  },
  {
    name: "reject/NonCanonicalNumeric/d9001800",
    hex: "d9001800",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "tag 24 in 3-byte head (should be d818)",
  },
  {
    name: "reject/NonCanonicalNumeric/f800",
    hex: "f800",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "simple 0 via 2-byte head: head-minimality check in readHeaderVarint precedes simple-value validation",
  },
  {
    name: "reject/NonCanonicalNumeric/f814",
    hex: "f814",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "ORDER PROOF: 'false' (20) via 2-byte head is NonCanonicalNumeric, NOT InvalidSimpleValue",
  },
  {
    name: "reject/NonCanonicalNumeric/f817",
    hex: "f817",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "simple 23 via 2-byte head - top of the f800-f817 NonCanonicalNumeric band",
  },
  {
    name: "reject/NonCanonicalNumeric/fb4045000000000000",
    hex: "fb4045000000000000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "42.0 as f64: re-encode reduces to int 182a (checkCanonicalEncoding L306)",
  },
  {
    name: "reject/NonCanonicalNumeric/fa42280000",
    hex: "fa42280000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "42.0 as f32 reduces to int",
  },
  {
    name: "reject/NonCanonicalNumeric/f95140",
    hex: "f95140",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "42.0 as f16 reduces to int - integral floats reduce even at the smallest width",
  },
  {
    name: "reject/NonCanonicalNumeric/f94200",
    hex: "f94200",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "3.0 as f16 reduces to int 03",
  },
  {
    name: "reject/NonCanonicalNumeric/f93c00",
    hex: "f93c00",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "1.0 as f16 reduces to int 01",
  },
  {
    name: "reject/NonCanonicalNumeric/f9bc00",
    hex: "f9bc00",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "-1.0 as f16 reduces to negative int 20",
  },
  {
    name: "reject/NonCanonicalNumeric/fac0a00000",
    hex: "fac0a00000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "-5.0 as f32 reduces to negative int 24",
  },
  {
    name: "reject/NonCanonicalNumeric/fbc000000000000000",
    hex: "fbc000000000000000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "-2.0 as f64 reduces to negative int 21",
  },
  {
    name: "reject/NonCanonicalNumeric/fa47c35000",
    hex: "fa47c35000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "100000.0 as f32 reduces to int 1a000186a0",
  },
  {
    name: "reject/NonCanonicalNumeric/fb43e0000000000000",
    hex: "fb43e0000000000000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "2^63 as f64 reduces to uint 1b8000000000000000 (bigint reduction path)",
  },
  {
    name: "reject/NonCanonicalNumeric/fa3fc00000",
    hex: "fa3fc00000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "1.5 as f32 when f16 f93e00 suffices",
  },
  {
    name: "reject/NonCanonicalNumeric/fb3ff8000000000000",
    hex: "fb3ff8000000000000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "1.5 as f64 when f16 suffices",
  },
  {
    name: "reject/NonCanonicalNumeric/fa3f000000",
    hex: "fa3f000000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "0.5 as f32 when f16 f93800 suffices",
  },
  {
    name: "reject/NonCanonicalNumeric/fb3fe0000000000000",
    hex: "fb3fe0000000000000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "0.5 as f64 when f16 suffices",
  },
  {
    name: "reject/NonCanonicalNumeric/fb3fb99999a0000000",
    hex: "fb3fb99999a0000000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "0.10000000149011612 (exactly f32 0x3dcccccd) widened to f64 - must be fa3dcccccd",
  },
  {
    name: "reject/NonCanonicalNumeric/fb7ff8000000000000",
    hex: "fb7ff8000000000000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "f64 quiet NaN: every NaN must be canonical f97e00",
  },
  {
    name: "reject/NonCanonicalNumeric/fa7fc00000",
    hex: "fa7fc00000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "f32 quiet NaN -> f97e00",
  },
  {
    name: "reject/NonCanonicalNumeric/f97e01",
    hex: "f97e01",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "f16 NaN with nonzero payload",
  },
  {
    name: "reject/NonCanonicalNumeric/f97c01",
    hex: "f97c01",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "f16 signalling NaN",
  },
  {
    name: "reject/NonCanonicalNumeric/f9fc01",
    hex: "f9fc01",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "f16 negative NaN",
  },
  {
    name: "reject/NonCanonicalNumeric/fb7ff0000000000001",
    hex: "fb7ff0000000000001",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "f64 signalling NaN payload",
  },
  {
    name: "reject/NonCanonicalNumeric/fa7f800000",
    hex: "fa7f800000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "+Infinity as f32: canonical form is f97c00",
  },
  {
    name: "reject/NonCanonicalNumeric/faff800000",
    hex: "faff800000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "-Infinity as f32: canonical form is f9fc00",
  },
  {
    name: "reject/NonCanonicalNumeric/fb7ff0000000000000",
    hex: "fb7ff0000000000000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "+Infinity as f64",
  },
  {
    name: "reject/NonCanonicalNumeric/fbfff0000000000000",
    hex: "fbfff0000000000000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "-Infinity as f64",
  },
  {
    name: "reject/NonCanonicalNumeric/f98000",
    hex: "f98000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "-0.0 as f16: dCBOR reduces -0.0 to integer 00",
  },
  {
    name: "reject/NonCanonicalNumeric/fa80000000",
    hex: "fa80000000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "-0.0 as f32 -> integer 00",
  },
  {
    name: "reject/NonCanonicalNumeric/fb8000000000000000",
    hex: "fb8000000000000000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "-0.0 as f64 -> integer 00",
  },
  {
    name: "reject/NonCanonicalNumeric/f90000",
    hex: "f90000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "+0.0 as f16 -> integer 00 (all zero floats reduce)",
  },
  {
    name: "reject/NonCanonicalNumeric/f97bff",
    hex: "f97bff",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "TRAP: f16 max 65504 is integral, reduces to 19ffe0 - rejected, not a valid f16",
  },
  {
    name: "reject/NonCanonicalNumeric/fa33800000",
    hex: "fa33800000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "5.9604644775390625e-8 as f32 when the f16 subnormal f90001 suffices",
  },
  {
    name: "reject/InvalidSimpleValue/e0",
    hex: "e0",
    expect: { ok: false, code: "InvalidSimpleValue" },
    note: "simple 0 (major 7 immediate, not false/true/null/float)",
  },
  {
    name: "reject/InvalidSimpleValue/ef",
    hex: "ef",
    expect: { ok: false, code: "InvalidSimpleValue" },
    note: "simple 15",
  },
  {
    name: "reject/InvalidSimpleValue/f0",
    hex: "f0",
    expect: { ok: false, code: "InvalidSimpleValue" },
    note: "simple 16",
  },
  {
    name: "reject/InvalidSimpleValue/f3",
    hex: "f3",
    expect: { ok: false, code: "InvalidSimpleValue" },
    note: "simple 19 (last before false)",
  },
  {
    name: "reject/InvalidSimpleValue/f7",
    hex: "f7",
    expect: { ok: false, code: "InvalidSimpleValue" },
    note: "undefined (simple 23) - dCBOR forbids it",
  },
  {
    name: "reject/InvalidSimpleValue/f818",
    hex: "f818",
    expect: { ok: false, code: "InvalidSimpleValue" },
    note: "simple 24: passes head-minimality (24>=24), then fails simple dispatch - first 2-byte InvalidSimpleValue",
  },
  {
    name: "reject/InvalidSimpleValue/f820",
    hex: "f820",
    expect: { ok: false, code: "InvalidSimpleValue" },
    note: "simple 32",
  },
  {
    name: "reject/InvalidSimpleValue/f8ff",
    hex: "f8ff",
    expect: { ok: false, code: "InvalidSimpleValue" },
    note: "simple 255",
  },
  {
    name: "reject/InvalidUtf8/62c328",
    hex: "62c328",
    expect: { ok: false, code: "InvalidUtf8" },
    note: "0xc3 lead byte followed by invalid continuation 0x28",
  },
  {
    name: "reject/InvalidUtf8/62c080",
    hex: "62c080",
    expect: { ok: false, code: "InvalidUtf8" },
    note: "overlong 2-byte encoding of NUL",
  },
  {
    name: "reject/InvalidUtf8/63eda080",
    hex: "63eda080",
    expect: { ok: false, code: "InvalidUtf8" },
    note: "CESU-8 lone surrogate U+D800 (ed a0 80)",
  },
  {
    name: "reject/InvalidUtf8/61c3",
    hex: "61c3",
    expect: { ok: false, code: "InvalidUtf8" },
    note: "declared length covers only the lead byte of a 2-byte sequence",
  },
  {
    name: "reject/InvalidUtf8/64f4908080",
    hex: "64f4908080",
    expect: { ok: false, code: "InvalidUtf8" },
    note: "codepoint U+110000 above Unicode max",
  },
  {
    name: "reject/InvalidUtf8/61ff",
    hex: "61ff",
    expect: { ok: false, code: "InvalidUtf8" },
    note: "0xff is never valid in UTF-8",
  },
  {
    name: "reject/NonCanonicalString/6365cc81",
    hex: "6365cc81",
    expect: { ok: false, code: "NonCanonicalString" },
    note: "'e' + combining acute U+0301 (NFD) - NFC composes to U+00E9",
  },
  {
    name: "reject/NonCanonicalString/66e18480e185a1",
    hex: "66e18480e185a1",
    expect: { ok: false, code: "NonCanonicalString" },
    note: "decomposed Hangul jamo U+1100 U+1161 - NFC composes to U+AC00",
  },
  {
    name: "reject/NonCanonicalString/63e284ab",
    hex: "63e284ab",
    expect: { ok: false, code: "NonCanonicalString" },
    note: "U+212B ANGSTROM SIGN - NFC singleton maps to U+00C5",
  },
  {
    name: "reject/UnusedData/0000",
    hex: "0000",
    expect: { ok: false, code: "UnusedData" },
    note: "uint 0 decoded, 1 trailing byte (details.count=1)",
  },
  {
    name: "reject/UnusedData/f6f6",
    hex: "f6f6",
    expect: { ok: false, code: "UnusedData" },
    note: "null decoded, trailing null byte",
  },
  {
    name: "reject/UnusedData/4100ff",
    hex: "4100ff",
    expect: { ok: false, code: "UnusedData" },
    note: "complete 1-byte bytestring + trailing 0xff",
  },
  {
    name: "reject/DuplicateMapKey/a201010102",
    hex: "a201010102",
    expect: { ok: false, code: "DuplicateMapKey" },
    note: "map {1:1, 1:2}: second key byte-equal to max - has() check fires BEFORE order check",
  },
  {
    name: "reject/MisorderedMapKey/a202000100",
    hex: "a202000100",
    expect: { ok: false, code: "MisorderedMapKey" },
    note: "same-length int keys descending (2 then 1)",
  },
  {
    name: "reject/MisorderedMapKey/a21818001700",
    hex: "a21818001700",
    expect: { ok: false, code: "MisorderedMapKey" },
    note: "key 24 (2-byte 1818) then key 23 (1-byte 17): shorter/smaller encoding must sort first (0x17<0x18)",
  },
  {
    name: "reject/MisorderedMapKey/a21818000100",
    hex: "a21818000100",
    expect: { ok: false, code: "MisorderedMapKey" },
    note: "2-byte key head 1818 then 1-byte key 01",
  },
  {
    name: "reject/MisorderedMapKey/a26161000100",
    hex: "a26161000100",
    expect: { ok: false, code: "MisorderedMapKey" },
    note: 'text key "a" (6161) then int key 1 (01): int head byte sorts before text head',
  },
  {
    name: "reject/DuplicateMapKey/a3010002000100",
    hex: "a3010002000100",
    expect: { ok: false, code: "DuplicateMapKey" },
    note: "3-entry map: third key duplicates a NON-max earlier key (1) - still DuplicateMapKey, not Misordered",
  },
  {
    name: "reject/Underrun/5b0020000000000000",
    hex: "5b0020000000000000",
    expect: { ok: false, code: "Underrun" },
    note: "bytestring length 2^53: narrowInteger keeps it bigint (> MAX_SAFE_INTEGER); unsatisfiable body -> Underrun, matching Rust's usize bounds check",
  },
  {
    name: "reject/Underrun/5bffffffffffffffff",
    hex: "5bffffffffffffffff",
    expect: { ok: false, code: "Underrun" },
    note: "bytestring length 2^64-1 (bigint)",
  },
  {
    name: "reject/Underrun/7b0020000000000000",
    hex: "7b0020000000000000",
    expect: { ok: false, code: "Underrun" },
    note: "text length 2^53 (bigint)",
  },
  {
    name: "reject/Underrun/7bffffffffffffffff",
    hex: "7bffffffffffffffff",
    expect: { ok: false, code: "Underrun" },
    note: "text length 2^64-1 (bigint)",
  },
  {
    name: "reject/NonCanonicalNumeric/811817",
    hex: "811817",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "nested: non-minimal int head inside array",
  },
  {
    name: "reject/InvalidSimpleValue/81f7",
    hex: "81f7",
    expect: { ok: false, code: "InvalidSimpleValue" },
    note: "nested: undefined inside array",
  },
  {
    name: "reject/UnsupportedHeaderValue/811c",
    hex: "811c",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "nested: headerValue 28 inside array",
  },
  {
    name: "reject/Underrun/8161",
    hex: "8161",
    expect: { ok: false, code: "Underrun" },
    note: "nested: truncated text body inside array",
  },
  {
    name: "reject/InvalidUtf8/8162c328",
    hex: "8162c328",
    expect: { ok: false, code: "InvalidUtf8" },
    note: "nested: invalid UTF-8 inside array",
  },
  {
    name: "reject/DuplicateMapKey/81a201010102",
    hex: "81a201010102",
    expect: { ok: false, code: "DuplicateMapKey" },
    note: "nested: duplicate-key map inside array",
  },
  {
    name: "reject/MisorderedMapKey/81a202000100",
    hex: "81a202000100",
    expect: { ok: false, code: "MisorderedMapKey" },
    note: "nested: misordered map inside array",
  },
  {
    name: "reject/NonCanonicalNumeric/81fb4045000000000000",
    hex: "81fb4045000000000000",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "nested: integer-reducible f64 inside array",
  },
  {
    name: "reject/Underrun/82005b0020000000000000",
    hex: "82005b0020000000000000",
    expect: { ok: false, code: "Underrun" },
    note: "nested: bigint bytestring length as 2nd array element",
  },
  {
    name: "reject/NonCanonicalNumeric/a1001817",
    hex: "a1001817",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "nested: non-minimal int as map VALUE",
  },
  {
    name: "reject/InvalidSimpleValue/a100f7",
    hex: "a100f7",
    expect: { ok: false, code: "InvalidSimpleValue" },
    note: "nested: undefined as map value",
  },
  {
    name: "reject/InvalidSimpleValue/a1f700",
    hex: "a1f700",
    expect: { ok: false, code: "InvalidSimpleValue" },
    note: "nested: undefined as map KEY (key decode fails before setNext)",
  },
  {
    name: "reject/NonCanonicalNumeric/a1181700",
    hex: "a1181700",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "nested: non-minimal int as map key",
  },
  {
    name: "reject/UnsupportedHeaderValue/a1005f",
    hex: "a1005f",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "nested: indefinite bytestring as map value",
  },
  {
    name: "reject/NonCanonicalNumeric/c11817",
    hex: "c11817",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "nested: non-minimal int as tag content",
  },
  {
    name: "reject/InvalidSimpleValue/c1f7",
    hex: "c1f7",
    expect: { ok: false, code: "InvalidSimpleValue" },
    note: "nested: undefined as tag content",
  },
  {
    name: "reject/UnsupportedHeaderValue/c15f",
    hex: "c15f",
    expect: { ok: false, code: "UnsupportedHeaderValue" },
    note: "nested: indefinite bytestring as tag content",
  },
  {
    name: "reject/InvalidUtf8/c162c328",
    hex: "c162c328",
    expect: { ok: false, code: "InvalidUtf8" },
    note: "nested: invalid UTF-8 as tag content",
  },
  {
    name: "reject/MisorderedMapKey/c1a202000100",
    hex: "c1a202000100",
    expect: { ok: false, code: "MisorderedMapKey" },
    note: "nested: misordered map inside tag",
  },
  {
    name: "reject/NonCanonicalNumeric/c1f97e01",
    hex: "c1f97e01",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "nested: non-canonical NaN inside tag",
  },
  {
    name: "reject/Underrun/da000001",
    hex: "da000001",
    expect: { ok: false, code: "Underrun" },
    note: "tag 5-byte head, 3 of 4 arg bytes",
  },
  {
    name: "reject/Underrun/db00000000000001",
    hex: "db00000000000001",
    expect: { ok: false, code: "Underrun" },
    note: "tag 9-byte head, 7 of 8 arg bytes",
  },
  {
    name: "reject/NonCanonicalNumeric/da0000001800",
    hex: "da0000001800",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "tag 24 in 5-byte head (should be d818)",
  },
  {
    name: "reject/NonCanonicalNumeric/db000000000000001800",
    hex: "db000000000000001800",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "tag 24 in 9-byte head",
  },
  {
    name: "reject/NonCanonicalNumeric/da0000ffff00",
    hex: "da0000ffff00",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "tag 65535 in 5-byte head at the <=0xffff boundary",
  },
  {
    name: "reject/NonCanonicalNumeric/db00000000ffffffff00",
    hex: "db00000000ffffffff00",
    expect: { ok: false, code: "NonCanonicalNumeric" },
    note: "tag 2^32-1 in 9-byte head at the <=0xffffffff boundary",
  },
  {
    name: "reject/Underrun/7818",
    hex: "7818",
    expect: { ok: false, code: "Underrun" },
    note: "text 2-byte length head declares 24 body bytes, has 0",
  },
  {
    name: "reject/Underrun/5901f4",
    hex: "5901f4",
    expect: { ok: false, code: "Underrun" },
    note: "bytestring 3-byte length head truncated (1 of 2 length bytes)",
  },
  {
    name: "reject/InvalidSimpleValue/82f7f6",
    hex: "82f7f6",
    expect: { ok: false, code: "InvalidSimpleValue" },
    note: "undefined as first array element, decode stops there",
  },
  {
    name: "reject/Underrun/a20102616162",
    hex: "a20102616162",
    expect: { ok: false, code: "Underrun" },
    note: "2-entry map second value is a text head with missing body",
  },
  { name: "accept/00", hex: "00", expect: { ok: true }, note: "0 - minimal immediate uint" },
  { name: "accept/17", hex: "17", expect: { ok: true }, note: "23 - max 1-byte uint head" },
  {
    name: "accept/1818",
    hex: "1818",
    expect: { ok: true },
    note: "24 - min legal 2-byte uint head",
  },
  { name: "accept/18ff", hex: "18ff", expect: { ok: true }, note: "255 - max 2-byte" },
  { name: "accept/190100", hex: "190100", expect: { ok: true }, note: "256 - min legal 3-byte" },
  { name: "accept/19ffff", hex: "19ffff", expect: { ok: true }, note: "65535 - max 3-byte" },
  {
    name: "accept/1a00010000",
    hex: "1a00010000",
    expect: { ok: true },
    note: "65536 - min legal 5-byte",
  },
  {
    name: "accept/1affffffff",
    hex: "1affffffff",
    expect: { ok: true },
    note: "4294967295 - max 5-byte",
  },
  {
    name: "accept/1b0000000100000000",
    hex: "1b0000000100000000",
    expect: { ok: true },
    note: "4294967296 - min legal 9-byte",
  },
  {
    name: "accept/1bffffffffffffffff",
    hex: "1bffffffffffffffff",
    expect: { ok: true },
    note: "2^64-1 - max uint, decodes to bigint via narrowInteger",
  },
  { name: "accept/20", hex: "20", expect: { ok: true }, note: "-1" },
  { name: "accept/37", hex: "37", expect: { ok: true }, note: "-24 - max 1-byte negative head" },
  {
    name: "accept/3818",
    hex: "3818",
    expect: { ok: true },
    note: "-25 - min legal 2-byte negative",
  },
  { name: "accept/38ff", hex: "38ff", expect: { ok: true }, note: "-256" },
  { name: "accept/390100", hex: "390100", expect: { ok: true }, note: "-257" },
  {
    name: "accept/3b0000000100000000",
    hex: "3b0000000100000000",
    expect: { ok: true },
    note: "-4294967297 - min legal 9-byte negative",
  },
  {
    name: "accept/3bffffffffffffffff",
    hex: "3bffffffffffffffff",
    expect: { ok: true },
    note: "-2^64 - the 65-bit negative edge that only major-1 can express",
  },
  {
    name: "accept/f97e00",
    hex: "f97e00",
    expect: { ok: true },
    note: "canonical NaN - the ONLY legal NaN encoding",
  },
  {
    name: "accept/f97c00",
    hex: "f97c00",
    expect: { ok: true },
    note: "+Infinity - canonical f16 form",
  },
  {
    name: "accept/f9fc00",
    hex: "f9fc00",
    expect: { ok: true },
    note: "-Infinity - canonical f16 form",
  },
  {
    name: "accept/f90001",
    hex: "f90001",
    expect: { ok: true },
    note: "min f16 subnormal 5.960464477539063e-8 (2-byte arg 0x0001 <= 0xff allowed because header is exactly 0xf9)",
  },
  {
    name: "accept/f903ff",
    hex: "f903ff",
    expect: { ok: true },
    note: "max f16 subnormal 6.097555160522461e-5",
  },
  {
    name: "accept/f93e00",
    hex: "f93e00",
    expect: { ok: true },
    note: "1.5 - canonical f16, non-integral so no reduction",
  },
  {
    name: "accept/f93bff",
    hex: "f93bff",
    expect: { ok: true },
    note: "0.99951171875 - largest f16 below 1 (contrast: f97bff/65504 is REJECTED because integral)",
  },
  {
    name: "accept/fa3dcccccd",
    hex: "fa3dcccccd",
    expect: { ok: true },
    note: "0.1f32 = 0.10000000149011612 - needs f32, f16 round-trip fails",
  },
  {
    name: "accept/fa3f8ccccd",
    hex: "fa3f8ccccd",
    expect: { ok: true },
    note: "1.1f32 = 1.100000023841858 - needs f32",
  },
  {
    name: "accept/fa00000001",
    hex: "fa00000001",
    expect: { ok: true },
    note: "min f32 subnormal 1.401298464324817e-45 (4-byte arg <= 0xffff allowed only under 0xfa)",
  },
  {
    name: "accept/fa7f7fffff",
    hex: "fa7f7fffff",
    expect: { ok: true },
    note: "f32 max 3.4028234663852886e38 - integral value but far above u64 range, stays float",
  },
  {
    name: "accept/fa5f800000",
    hex: "fa5f800000",
    expect: { ok: true },
    note: "2^64 exactly as f32 - whole-valued but exceeds u64 by 1, so no integer reduction",
  },
  {
    name: "accept/fb3ff199999999999a",
    hex: "fb3ff199999999999a",
    expect: { ok: true },
    note: "1.1 - needs full f64 (not f32-exact)",
  },
  {
    name: "accept/fb3fb999999999999a",
    hex: "fb3fb999999999999a",
    expect: { ok: true },
    note: "0.1 - canonical f64 (contrast with rejected fb3fb99999a0000000, the widened f32 value)",
  },
  {
    name: "accept/fb0000000000000001",
    hex: "fb0000000000000001",
    expect: { ok: true },
    note: "min f64 subnormal 5e-324 (8-byte arg <= 0xffffffff allowed only under 0xfb)",
  },
  {
    name: "accept/fb7e37e43c8800759c",
    hex: "fb7e37e43c8800759c",
    expect: { ok: true },
    note: "1e300 - integral but above 2^64 and not f32-exact, stays f64",
  },
  {
    name: "accept/f4",
    hex: "f4",
    expect: { ok: true },
    note: "false (only via 1-byte head; f814 form is rejected)",
  },
  { name: "accept/f5", hex: "f5", expect: { ok: true }, note: "true" },
  { name: "accept/f6", hex: "f6", expect: { ok: true }, note: "null" },
  { name: "accept/40", hex: "40", expect: { ok: true }, note: "empty bytestring" },
  { name: "accept/60", hex: "60", expect: { ok: true }, note: "empty text" },
  { name: "accept/80", hex: "80", expect: { ok: true }, note: "empty array" },
  { name: "accept/a0", hex: "a0", expect: { ok: true }, note: "empty map" },
  { name: "accept/a10102", hex: "a10102", expect: { ok: true }, note: "single-entry map {1:2}" },
  {
    name: "accept/a201000200",
    hex: "a201000200",
    expect: { ok: true },
    note: "canonical 2-entry map {1:0, 2:0} - keys strictly ascending",
  },
  {
    name: "accept/a20100616100",
    hex: "a20100616100",
    expect: { ok: true },
    note: 'mixed-type keys {1:0, "a":0} - int head byte 0x01 sorts before text head 0x61',
  },
  {
    name: "accept/62c3a9",
    hex: "62c3a9",
    expect: { ok: true },
    note: "NFC-composed é (U+00E9) - passes both UTF-8 and NFC checks",
  },
  {
    name: "accept/8181818100",
    hex: "8181818100",
    expect: { ok: true },
    note: "deeply nested arrays [[[[0]]]] - recursion propagates cleanly",
  },
  {
    name: "accept/c000",
    hex: "c000",
    expect: { ok: true },
    note: "tag 0 with content 0 - min 1-byte tag head (decode layer does not validate tag semantics)",
  },
  { name: "accept/d700", hex: "d700", expect: { ok: true }, note: "tag 23 - max 1-byte tag head" },
  {
    name: "accept/d81800",
    hex: "d81800",
    expect: { ok: true },
    note: "tag 24 - min legal 2-byte tag head",
  },
  {
    name: "accept/d8ff00",
    hex: "d8ff00",
    expect: { ok: true },
    note: "tag 255 - max 2-byte tag head",
  },
  {
    name: "accept/d9010000",
    hex: "d9010000",
    expect: { ok: true },
    note: "tag 256 - min legal 3-byte tag head",
  },
  {
    name: "accept/d9d9f700",
    hex: "d9d9f700",
    expect: { ok: true },
    note: "self-describe-CBOR tag 55799 wrapping 0",
  },
  {
    name: "accept/dbffffffffffffffff00",
    hex: "dbffffffffffffffff00",
    expect: { ok: true },
    note: "tag 2^64-1 (bigint tag value) - tags never hit OutOfRange",
  },
  { name: "accept/c1c100", hex: "c1c100", expect: { ok: true }, note: "tag-of-tag: 1(1(0))" },
  {
    name: "accept/83010203",
    hex: "83010203",
    expect: { ok: true },
    note: "plain 3-element array [1,2,3]",
  },
  {
    name: "accept/4401020304",
    hex: "4401020304",
    expect: { ok: true },
    note: "4-byte bytestring h'01020304'",
  },
  {
    name: "accept/da0001000000",
    hex: "da0001000000",
    expect: { ok: true },
    note: "tag 65536 via minimal 5-byte head wrapping 0",
  },
  {
    name: "accept/db000000010000000000",
    hex: "db000000010000000000",
    expect: { ok: true },
    note: "tag 2^32 via minimal 9-byte head wrapping 0",
  },
  {
    name: "accept/c24100",
    hex: "c24100",
    expect: { ok: true },
    note: "tag 2 + leading-zero magnitude: decodeCbor does NOT validate bignum canonicality (extraction layer does)",
  },
  {
    name: "accept/c340",
    hex: "c340",
    expect: { ok: true },
    note: "tag 3 + empty byte string decodes at the CBOR layer",
  },
  {
    name: "accept/c1c1c1c1c1c1c1c100",
    hex: "c1c1c1c1c1c1c1c100",
    expect: { ok: true },
    note: "8-deep tag chain",
  },
  {
    name: "accept/a2616101616202",
    hex: "a2616101616202",
    expect: { ok: true },
    note: "canonical 2-entry text-key map",
  },
  {
    name: "accept/5818000000000000000000000000000000000000000000000000",
    hex: "5818000000000000000000000000000000000000000000000000",
    expect: { ok: true },
    note: "24-byte bytestring via minimal 2-byte length head",
  },
  {
    name: "accept/7818616161616161616161616161616161616161616161616161",
    hex: "7818616161616161616161616161616161616161616161616161",
    expect: { ok: true },
    note: "24-char text via minimal 2-byte length head",
  },
  {
    name: "accept/9818000000000000000000000000000000000000000000000000",
    hex: "9818000000000000000000000000000000000000000000000000",
    expect: { ok: true },
    note: "24-element array via minimal 2-byte count head",
  },
];

// Fixture names must be unique.
{
  const seen = new Set<string>();
  for (const { name } of decodeCorpus) {
    if (seen.has(name)) throw new Error(`duplicate decode-corpus name: ${name}`);
    seen.add(name);
  }
}
